// lib/booking-catalog.ts
// Server-side source of truth for booking service prices/durations.
// Mirrors the SERVICE_CATALOG in app/book/page.tsx (id, name, price, duration).
// NEVER trust price/duration sent from the client for /api/booking-checkout —
// look them up here instead. If a new service is added to the booking page,
// it must be added here too or checkout will reject it with "Unknown service".

export interface CatalogService {
  name: string;
  price: number;    // dollars
  duration: number; // minutes
}

export const BOOKING_SERVICES: Record<string, CatalogService> = {
  "w-brazilian":        { name: "Brazilian Wax",              price: 50,  duration: 45 },
  "w-bikini-line":      { name: "Bikini Line",                 price: 30,  duration: 20 },
  "w-french":           { name: "French Bikini",                price: 40,  duration: 30 },
  "w-full-leg":         { name: "Full Leg",                     price: 55,  duration: 50 },
  "w-half-leg":         { name: "Half Leg",                     price: 45,  duration: 35 },
  "w-full-arm":         { name: "Full Arm",                     price: 45,  duration: 40 },
  "w-half-arm":         { name: "Half Arm",                     price: 30,  duration: 25 },
  "w-underarm":         { name: "Underarm",                     price: 20,  duration: 20 },
  "w-stomach-strip":    { name: "Stomach Strip",                price: 20,  duration: 15 },
  "w-full-stomach":     { name: "Full Stomach",                 price: 40,  duration: 25 },
  "w-toes":             { name: "Toes",                         price: 10,  duration: 10 },
  "w-feet":             { name: "Feet",                         price: 20,  duration: 15 },
  "w-back":             { name: "Back",                         price: 45,  duration: 40 },
  "w-full-buttock":     { name: "Full Buttock",                 price: 30,  duration: 20 },
  "w-cheeks":           { name: "Between the Cheeks",           price: 15,  duration: 10 },
  "w-chest":            { name: "Chest",                        price: 15,  duration: 15 },
  "w-full-body":        { name: "Full Body Wax",                price: 140, duration: 90 },
  "w-eyebrow":          { name: "Eyebrow",                      price: 15,  duration: 20 },
  "w-upper-lip":        { name: "Upper Lip",                    price: 10,  duration: 10 },
  "w-chin":             { name: "Chin",                         price: 15,  duration: 12 },
  "w-cheekbones":       { name: "Cheekbones",                   price: 12,  duration: 15 },
  "w-sideburns":        { name: "Sideburns",                    price: 12,  duration: 10 },
  "m-full-arms":        { name: "Full Arms",                    price: 60,  duration: 45 },
  "m-half-arm":         { name: "Half Arm",                     price: 35,  duration: 25 },
  "m-back":             { name: "Back Wax",                     price: 50,  duration: 45 },
  "m-chest":            { name: "Chest",                        price: 40,  duration: 32 },
  "m-underarm":         { name: "Underarms",                    price: 30,  duration: 20 },
  "m-brozilian":        { name: "Brozilian",                    price: 60,  duration: 50 },
  "m-full-legs":        { name: "Full Legs",                    price: 70,  duration: 55 },
  "m-half-legs":        { name: "Half Legs",                    price: 45,  duration: 35 },
  "m-full-butt":        { name: "Full Butt",                    price: 40,  duration: 20 },
  "m-cheeks":           { name: "Between the Cheeks",           price: 20,  duration: 10 },
  "m-stomach-strip":    { name: "Stomach Strip",                price: 30,  duration: 15 },
  "m-full-stomach":     { name: "Full Stomach",                 price: 60,  duration: 25 },
  "m-feet":             { name: "Feet",                         price: 20,  duration: 15 },
  "m-toes":             { name: "Toes",                         price: 10,  duration: 10 },
  "m-full-body":        { name: "Full Body Wax",                price: 160, duration: 90 },
  "m-eyebrows":         { name: "Eyebrows",                     price: 20,  duration: 20 },
  "m-upper-lip":        { name: "Upper Lip",                    price: 15,  duration: 10 },
  "m-chin":             { name: "Chin",                         price: 20,  duration: 12 },
  "m-cheekbones":       { name: "Cheekbones",                   price: 20,  duration: 15 },
  "m-sideburns":        { name: "Sideburns",                    price: 15,  duration: 10 },
  "m-beard":            { name: "Beard",                        price: 50,  duration: 30 },
  "m-nose":             { name: "Nose Wax",                     price: 10,  duration: 10 },
  "add-high-freq-f":    { name: "High Frequency Wand",          price: 15,  duration: 10 },
  "add-oxygen-f":       { name: "Oxygen Spray",                 price: 30,  duration: 10 },
  "add-ultrasonic-f":   { name: "Ultrasonic Vibration",         price: 15,  duration: 10 },
  "add-lifting-f":      { name: "Skin Lifting",                 price: 10,  duration: 10 },
  "add-cold-f":         { name: "Cold Hammer",                  price: 10,  duration: 10 },
  "add-scrubber-f":     { name: "Skin Scrubber",                price: 20,  duration: 10 },
  "add-hydra-f":        { name: "Hydra Facial",                 price: 80,  duration: 30 },
  "add-microderm-f":    { name: "Microdermabrasion",            price: 40,  duration: 20 },
  "add-dermaplane-f":   { name: "Dermaplaning",                 price: 45,  duration: 15 },
  "add-high-freq-b":    { name: "High Frequency Wand",          price: 35,  duration: 10 },
  "add-oxygen-b":       { name: "Oxygen Spray",                 price: 60,  duration: 10 },
  "add-ultrasonic-b":   { name: "Ultrasonic Vibration",         price: 30,  duration: 10 },
  "add-lifting-b":      { name: "Skin Lifting",                 price: 45,  duration: 10 },
  "add-cold-b":         { name: "Cold Hammer",                  price: 30,  duration: 10 },
  "add-scrubber-b":     { name: "Skin Scrubber",                price: 40,  duration: 10 },
  "add-microderm-b":    { name: "Microdermabrasion",            price: 80,  duration: 20 },
  "add-hydra-b":        { name: "Hydra Treatment",              price: 160, duration: 45 },
  "add-vajacial-b":     { name: "Vajacial",                     price: 25,  duration: 30 },
  "add-head":           { name: "Head Massage",                 price: 25,  duration: 10 },
  "add-arms":           { name: "Arms / Hands",                 price: 15,  duration: 10 },
  "add-decollete":      { name: "Décolleté Massage / Shoulders",price: 40,  duration: 15 },
  "add-back":           { name: "Back Massage",                 price: 60,  duration: 15 },
  "add-legs":           { name: "Leg Massage",                  price: 50,  duration: 15 },
  "add-feet":           { name: "Feet Massage",                 price: 35,  duration: 10 },
  "add-10min":          { name: "Add 10 Minutes",               price: 25,  duration: 10 },
  "facial-t1":          { name: "Tier 1 Facial",                 price: 50,  duration: 30 },
  "facial-t2":          { name: "Tier 2 Facial",                 price: 80,  duration: 60 },
  "facial-t3":          { name: "Tier 3 Facial",                 price: 90,  duration: 75 },
  "vaj-t1":             { name: "Vajacial Tier 1",                price: 70,  duration: 30 },
  "vaj-t2":             { name: "Vajacial Tier 2",                price: 80,  duration: 45 },
  "vaj-t3":             { name: "Vajacial Tier 3",                price: 90,  duration: 60 },
  "bacial-t1":          { name: "Bacial Tier 1",                  price: 75,  duration: 45 },
  "bacial-t2":          { name: "Bacial Tier 2",                  price: 95,  duration: 60 },
};
